### ISSUE TITLE
PolyGit is down

### ISSUE THREAD

**Issue by tstewart15** [PolymerLabs/polygit#7] opened 2016-08-24 19:46 UTC
Can't access PolyGit: polygit.org

First seen in this demo: http://jsbin.com/natavulijo/1/edit?html,console,output

**Comment by garlicnation** [comment] 2016-08-24 21:32
Duplicate of https://github.com/PolymerLabs/polygit2/issues/13
Other issue closed.

**Closed** 2016-08-24 21:33 UTC
